output_dir: C:\Users\ellis\OneDrive\Documents\University\Year-3\SGP\SGP_project\results\experiment_1\sis_adaptive
seed: 42
use_semantics: true
adaptive_threshold: false
elitism_size: 2
independent_runs: 30
max_generations: 1000
initial_depth: 5
final_depth: 7
max_final_depth: 9
tournament_size: 7
crossover_rate: 0.9
mutation_rate: 0.25
population_size: 200
max_semantic_threshold: 0.01
min_semantic_threshold: 0.005
shuffle: true
verbose: true
