adaptive_threshold: true
crossover_rate: 1.0
dataset_path: datasets/symbolic_regression.csv
elitism_size: 3
independent_runs: 30
max_generations: 200
initial_depth: 5
final_depth: 7
mutation_rate: 0
output_dir: results/
population_size: 126
project_name: SGP_project
seed: 42
use_semantics: true
semantic_threshold: 0.05
shuffle: true
tournament_size: 7
verbose: true
