adaptive_threshold: false
dataset_path: datasets/symbolic_regression.csv
elitism_size: 3
independent_runs: 30
max_generations: 300
initial_depth: 5
final_depth: 7
crossover_rate: 0.75
mutation_rate: 0.2
output_dir: results/
population_size: 250
project_name: SGP_project
seed: 42
use_semantics: true
semantic_threshold: 0.1
shuffle: true
tournament_size: 7
verbose: true
