output_dir: C:\Users\ellis\OneDrive\Documents\University\Year-3\SGP\SGP_project\results\dump\dump.txt
seed: 42
use_semantics: true
adaptive_threshold: true
elitism_size: 2
independent_runs: 10
max_generations: 1000
initial_depth: 3
final_depth: 5
tournament_size: 7
crossover_rate: 0.85
mutation_rate: 0.25
population_size: 200
semantic_threshold: 0.1
shuffle: true
verbose: true
